### ISSUE TITLE
[error] [WASI-NN] GGML backend: Error: prompt too long (570 tokens, max 508)

### ISSUE THREAD

**Issue by niranjanakella** [second-state/WasmEdge-WASINN-examples#50]
Hello, I was trying to prompt the new Zephyr model to summarize a long conversation and stumbled upon this error for input token limit. 

```
[2023-10-14 17:39:06.691] [error] [WASI-NN] GGML backend: Error: prompt too long (570 tokens, max 508)
thread 'main' panicked at src/main.rs:71:14:
called `Result::unwrap()` on an `Err` value: BackendError(InvalidArgument)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-10-14 17:39:06.692] [error] execution failed: unreachable, Code: 0x89
[2023-10-14 17:39:06.692] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x00007916
[2023-10-14 17:39:06.692] [error]     When executing function name: "_start"
```

How do I truncate and possible how to batch the input tokens for proper error free inference. 

@juntao @chenyukang Kindly guide.

**Comment by juntao** [comment]
Your client application must take care that the sequence is not greater than the context length. There are many ways to do this -- some compute and truncate the conversation in frontend JavaScript, some do it in LangChain. You can write similar logic in your rust program.

**Comment by niranjanakella** [comment]
@juntao I see that this is the same case with LLaMa2 model inference too. Since I am new to this, just a question - Why is the max limit 508? and is there any prebuilt function for batching, truncation & padding? or will have to write the logic for it? 

Thank you.

**Comment by juntao** [comment]
All models come with specific context lengths. You can read about it [here](https://agi-sphere.com/context-length/). 

Since we do not know what model the user is going to use, we have a preset context length of around 500 words. If your model can support longer context, you can increase the context length by appending `LLAMA_N_CTX=2048`  before the `wasmedge` command. That increases the context length to 2k. 

To manage the context length is the job of the application developer. Say you have a long conversation that exceeds the context length of the model, you will need to decide which part of the conversation is not important to your business and remove them. This the logic you have to write if you need a non trivial application.

**Comment by niranjanakella** [comment]
Highly appreciate the feed back. Exported `LLAMA_N_CTX=1024` and now the model is able to inference well. Thank a lot @juntao.
