### ISSUE TITLE
Issue running on ARM architecture 

### ISSUE THREAD

**Issue by niranjanakella** [second-state/WasmEdge-WASINN-examples#55]
I've spinned up an EC2 instance from AWS to check the performance. 

Config:
CPU: Amazon Linux 2023 AMI 2023.2.20231018.2 arm64 HVM kernel-6.1
GPU: c6g.xlarge 8GB 4 vCPU

Installed all the necessary packages:
```
sudo su
sudo apt update && apt upgrade
sudo reboot

#after reboot
sudo su
sudo apt install build-essential

sudo apt update && apt install -y libopenblas-dev

#installed rust 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"

#installing wasmedge
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml
source /root/.bashrc

git clone https://github.com/second-state/WasmEdge-WASINN-examples.git
cd WasmEdge-WASINN-examples/wasmedge-ggml-llama-interactive

#downloaded the model
curl -LO https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q5_K_M.gguf

#built successfully from source
cargo build --target=wasm32-wasi --release
cp target/wasm32-wasi/release/wasmedge-ggml-llama-interactive.wasm ./wasmedge-ggml-llama-interactive.wasm

#running the wasm application
wasmedge --dir .:. \
  --nn-preload default:GGML:CPU:llama-2-7b-chat.Q5_K_M.gguf \
  wasmedge-ggml-llama-interactive.wasm default

```

ERROR:
free(): invalid pointer
Aborted (core dumped)

**Comment by hydai** [comment]
Duplicated issue. Closing this. Let's track it in #48

**Comment by niranjanakella** [comment]
@hydai  I also used an x86 architecture Ubuntu EC2 and tried to run it. Though it runs the inference speed is very very slow. Would it work on Amazon Linux? x86? 

And why is it slower on Ubuntu? even when mentioning that ExecutionTarger:GPU

**Comment by hydai** [comment]
The reason is that our pre-built plugin on Ubuntu will use openblas by default, which uses CPU only.
We are going to release several assets for the different proposes, such as cuBLAS.

The combination of ARCH, OS, and GPU is various, we are trying to figure out which will be the most general one for release.

**Comment by niranjanakella** [comment]
Woww thanks for such quick reply. Just one small follow up question is that, even though we use CPU only, the model inference should be descent right? 

I see that we are leverating the ARM64 + Metal on mac. But apart from that I just want to know which combination would would well? to make it work faster on AWS Lambdas

**Comment by hydai** [comment]
The hardware should only affect the performance.

The following scores are based on the llama-2-7b-chat.Q5_K_M.gguf model.

| ARCH | ARCH defails | RAM(GB) | GPU | VRAM(GB) | OS | Accelerate framework | TPS |
| -- | -- | -- | -- | -- | -- | -- | -- |
| X86_64(Intel/AMD) | i7-10700 | 128 | 0 | 0 | Ubuntu 22.04 | openBLAS | 6.23 |
| X86_64(Intel/AMD) | g5.4xlarge | 64 | A10G | 24 | Ubuntu 22.04 | cuda11 + cuBLAS | 73.07 |
| AARCH64(ARM/Apple Silicon) | M2 Max | 64 | M2 Max | 64 | macOS 13.6 | Metal | 45.03 |
| AARCH64(ARM/Apple Silicon) | Jetson Orin | 64 | Jetson Orin | 64 | Ubuntu 22.04 | cuda11 + cuBLAS | 17.92 | 

Using Linux + cuBLAS can help due to the above table.

I need to learn about the scores on AWS Lambdas. Would you happen to have any information?

**Comment by niranjanakella** [comment]
I am yet to run it on Lambdas. I am currently testing it out on AWS Amazon Linux EC2 instance. Since Lambdas also use Amazon Linux. Will update once I succeed to run on them.
